name: Deploy мозаика62.рф

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.MOZAIKA_HOST }}
          username: ${{ secrets.MOZAIKA_USER }}
          key: ${{ secrets.MOZAIKA_KEY }}
          script: |
            # ========== ДЛЯ ПЕРВОЙ ИНИЦИАЛИЗАЦИИ ==========
            # cd /var/www/u1538455/data/www/мозаика62.рф/wp-content/themes
            # git clone https://github.com/site100ru/mozaika62-rf.git site100mozaika

            git fetch origin
            git reset --hard origin/main
            
            #cd ~/mozaika/public_html/wp-content/themes/site100mozaika
            #git pull

            # ========== ЧТО МЕНЯТЬ ДЛЯ ДРУГИХ ПРОЕКТОВ ==========
            # мозаика62.рф - доменное имя сайта
            # new - название папки темы в /themes/